<a href="https://colab.research.google.com/github/Arka2001/Dive-into-Deep-Learning-Notes/blob/main/Dive_to_Deep_Learning_2_3_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**LINEAR ALGEBRA**

**Scalars**

A scalar is aphysical quantity having technically zero dimensions. It only has magnitude and no other dimension with is. It is basically a constant numerical value. Like, 5,9,23,20, etc. are all constant scalar values.

In [2]:
#In PyTorch scalar values are represented as a 1x1 dimension vector. Such as follows:
import torch
scalar1 = torch.tensor([3.0])
scalar2 = torch.tensor([4.0])

In [3]:
scalar1+scalar2, scalar1-scalar2,scalar1*scalar2,scalar1/scalar2,scalar1//scalar2,scalar1**scalar2

(tensor([7.]),
 tensor([-1.]),
 tensor([12.]),
 tensor([0.7500]),
 tensor([0.]),
 tensor([81.]))

**Vectors**

Vectors are simply one-dimensional quantities. To put it in a more simple manner, we can consider a vector to be a list of values. For example, [1,2,3,4] is considered as a vector.

In [4]:
#Using, PyTorch a vector can be easily created using the arange command.
vector = torch.arange(10)
vector

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Any element of the vector can be accessed through the index of that vector. For instance in this case, the index for 2 is 2.
vector[2]  #<- vector_name[index of element]

tensor(2)

In [9]:
#Length of a vector can be found by the inbuilt len() function in Python
len(vector)

10

In [12]:
#To get the shape of the vector you can use the .shape function
vector.shape

torch.Size([10])

**Matrices**

Just like One-dimensional tensors are called vectors, similarly, two-dimensional tensors are called matrices.