**LINEAR ALGEBRA**

**Scalars**

A scalar is aphysical quantity having technically zero dimensions. It only has magnitude and no other dimension with is. It is basically a constant numerical value. Like, 5,9,23,20, etc. are all constant scalar values.

In [1]:
#In PyTorch scalar values are represented as a 1x1 dimension vector. Such as follows:
import torch
scalar1 = torch.tensor([3.0])
scalar2 = torch.tensor([4.0])

In [2]:
scalar1+scalar2, scalar1-scalar2,scalar1*scalar2,scalar1/scalar2,scalar1//scalar2,scalar1**scalar2

(tensor([7.]),
 tensor([-1.]),
 tensor([12.]),
 tensor([0.7500]),
 tensor([0.]),
 tensor([81.]))

**Vectors**

Vectors are simply one-dimensional quantities. To put it in a more simple manner, we can consider a vector to be a list of values. For example, [1,2,3,4] is considered as a vector.

In [3]:
#Using, PyTorch a vector can be easily created using the arange command.
vector = torch.arange(10)
vector

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Any element of the vector can be accessed through the index of that vector. For instance in this case, the index for 2 is 2.
vector[2]  #<- vector_name[index of element]

tensor(2)

In [5]:
#Length of a vector can be found by the inbuilt len() function in Python
len(vector)

10

In [6]:
#To get the shape of the vector you can use the .shape function
vector.shape

torch.Size([10])

**Matrices**

Just like One-dimensional tensors are called vectors, similarly, two-dimensional tensors are called matrices. Matrices can be created by first creating a vector and then by reshaping it. A matrix contains 2 dimensions, x and y.

In [7]:
matrix = torch.arange(20).reshape(5,4)
matrix

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [8]:
'''Elements of a matrix can also be accessed through indexing.
But in contrary to indexing in a vector, which requires only one index, indexing in a matrix requires 2 indices, one for the row and one for the column.
For example, if we want the element at row of index 2 and column of index 3 of the matrix mat, we would have to write mat[2][3] to get the element.
'''

matrix[2][3]

tensor(11)

The transpose of a matrix is when the columns and the rows interchange with each other. Say for instance we have a matrix '[[1,2],[3,4]]'. The transpose of this matrix would be '[[1,3],[2,4]]'. Notice that the elements of the primary diagonal, in this case 1 and 4 do not change their places. When writing code we can easily find the transpose of any given matrix.

In [9]:
#Transpose of matrix is given by
matrix.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

For a *symmetric* matrix, the transpose of the matrix is equal to the original matrix.

In [10]:
#Let us define a symmetric matrix A
A = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
A

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
#Let B be the transpose of A
B = A.T
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

As you can see that there is no difference between matrices B and A. We can also prove it by the following command.

In [12]:
A == B

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

Therefore we see that for a symmetric matrix A, A.T = A. Inversely, we can say that a matrix whose transpose is equal to that matrix itself is a **symmetric** matrix.

**Tensors**

Tensor is the general term for any dimensional array. One-dimensional tensors are called vectors, two-dimensional tensors are called matrices. Any higher order tensors do not have any specific names, they are simply called tensors. Tensors in PyTorch can be created using the torch.tensor() function. We can also create a vetor using the arange() function and then reshape it.

In [13]:
A = torch.arange(24).reshape(2,3,4)
A

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

Anything beyond 3 dimensions is very difficult for us to imagine. But using numpy and PyTorch tensors, we can work with and manipulate n-dimensional tensors or arrays

**Tensor Arithmetic - Basics**

Any n-dimensional tensor has a lot of functionalities which can be used for our benefit. Most important of these functionalities are the elementwise arithmetic operations between two tensors of the shape.

In [14]:
A = torch.arange(20).reshape(4,5)
B = torch.arange(3,23).reshape(4,5)

In [15]:
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [16]:
B

tensor([[ 3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22]])

In [17]:
A+B

tensor([[ 3,  5,  7,  9, 11],
        [13, 15, 17, 19, 21],
        [23, 25, 27, 29, 31],
        [33, 35, 37, 39, 41]])

Usually, we do not do elementwise multiplication of two tensors or rather matrices. The elementwise multiplication of two matrices is called *Hadamard* multiplication.

**Note: Make sure that whenever you perform elementwise operations on 2 matrices, the shpae of the matrices should be equal.**

In [18]:
A*B #Hadamard multiplication

tensor([[  0,   4,  10,  18,  28],
        [ 40,  54,  70,  88, 108],
        [130, 154, 180, 208, 238],
        [270, 304, 340, 378, 418]])

Multiplying or adding a tensor with a scalar quantity does not change the shape of the tensor. Rather each element of the tensor gets added or multiplied with the scalar quantity.

In [19]:
a = 5
A = torch.arange(9).reshape(3,3)
A

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [20]:
a + A

tensor([[ 5,  6,  7],
        [ 8,  9, 10],
        [11, 12, 13]])

In [21]:
a * A

tensor([[ 0,  5, 10],
        [15, 20, 25],
        [30, 35, 40]])

**Reduction**

Using tensors in Python can help us reduce our code and therefore increase efficiency. 

In [22]:
#We can find the sum of all elements in a tensor through the .sum() function
X = torch.arange(4,dtype=torch.float32)
X,X.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [23]:
A = torch.arange(20,dtype=torch.float32).reshape(5,4)
A.shape,A.sum()

(torch.Size([5, 4]), tensor(190.))

As we can see from the above cells and their outputs, the .sum() function reduces the original tensor to a one-dimensional vector. Therefore using this functionality, we can calculate the sum of elements in each row or column of the tensor, by specifying the axis.

In [24]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [25]:
sum_each_row = A.sum(axis=0) #Code for finding the sum of elements of each row
sum_each_row

tensor([40., 45., 50., 55.])

In [26]:
sum_each_col = A.sum(axis=1) #Code for finding the sum of elements of each column
sum_each_col

tensor([ 6., 22., 38., 54., 70.])

In [27]:
#Finding the mean of all elements in the tensor
A.mean(), A.sum()/A.numel()   #.numel() function returns the total number of elements present in the tensor

(tensor(9.5000), tensor(9.5000))

In [28]:
#Finding mean of elements present in along an axis, say mean of elements of each row
A.mean(axis=0),A.sum(axis=0)/A.shape[0] #.shape[0] returns the number of rows in the tensor, or rather the number of elements in each column

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

**Non-Reduction Sum**

Many a times, it would be helpful for you if you do not reduce the dimensions of the given tensor while finding the sum of all the elements.

In [29]:
#How to keep the dimensions same, i.e., find the non-reduction sum?

A_sum = A.sum(axis = 1,keepdims=True)
A_sum

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [30]:
A/A_sum

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [31]:
A.cumsum(axis=0) #Function to calculate the elementwise cumulative sum of the tensor. This does not reduce the dimensions of the tensor

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

**Dot Products**

Dot product is an integral part of Linear Algebra. Now what is dot product. Dot product of two tensors means the sum of the products of all the elements at the same positions at the two tensors.

In [32]:
x = torch.arange(4)
y = torch.arange(5,9)
x,y,torch.dot(x,y)

(tensor([0, 1, 2, 3]), tensor([5, 6, 7, 8]), tensor(44))

In [33]:
#Instead of the dot() function we can first perform elementwise multiplication operation and then find out the sum of the resultant tensor\
x*y,torch.sum(x*y)

(tensor([ 0,  6, 14, 24]), tensor(44))

**Matrix Vector Operations**

Using dot products, we can find the length of a resultant tensor of any two tensors. But using vector operations, we can get the magnitude as well as the other necessary dimensions required for a tensor. This is mopstly prevalent in matrices, because, matrices contain 2 dimensions, directions and magnitudes. Therefore using vector operations on any 2 matrices, we can get a resultant matrix, which will give us the direction and magnitude. In this section we are going to deal with products between a matrix and a vector

In [34]:
A #Matrix

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [35]:
x = torch.arange(4,dtype=torch.float32)#Vector
x

tensor([0., 1., 2., 3.])

In [36]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

**Matrix-Matrix Multiplication**

This is also known as matrix multiplication. The process of matrix multiplication is that if we are multiplying A*B, then each element of the first row of the resultant matrix is the sum of the products of corresponding elements in the first row of A and the corresponding numbered column of B. Similarly, each element of the second row of the resultant matrix is the sum of products of corresponding elements in second row of A and the corresponding numbered column of B.

Say, for instance, A = [[1,2,3],

[4,5,6],

[7,8,9]] 

and B = [[1,1,1]

,[2,2,2],

[3,3,3]]

Therefore AxB = 

[[1x1+2x2+3x3,1x1+2x2+3x3,1x1+2x2+3x3],

[4x1+5x2+6x3,4x1+5x2+6x3,4x1+5x2+6x3,],

[7x1+8x2+9x3,7x1+8x2+9x3,7x1+8x2+9x3]]

= [[14,14,14],

[32,32,32],

[50,50,50]]

One more thing to keep in mind is that for 2 vectors, if a matrix A has a shape nxm and matrix B has a shape mxp, then the resultant matrix AxB shall have a shape of nxp



In [37]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [38]:
B = torch.ones(4,3)
B

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [39]:
torch.mm(A,B)  #np.dot(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

**NORM**

The norm of a vector or a matrix is of 2 types. One is the L1 norm and the other is the L2 norm. 

The L1 norm is the sum of the absolute values of all the elements present in the vector or matrix.

The L2 norm is the sum of the squares of all the elements present in the vector or matrix.

In [40]:
#L2 Norm

x = torch.tensor([3.0,-4.0])     # np.array([3.0,-4.0])
torch.norm(x)   #np.linalg.norm(x)

tensor(5.)

In [41]:
#L1 Norm

torch.abs(x).sum()  #np.abs(x).sum()

tensor(7.)